target-version = "py310"

[lint]
ignore = [
    "ASYNC210",
    "ASYNC221",
    "S110",
    "BLE001",
    "B006",
    "B017",
    "C403",
    "C405",
    "C406",
    "C408",
    "C414",
    "DTZ001",
    "DTZ002",
    "DTZ005",
    "DTZ006",
    "DTZ007",
    "EXE001",
    "EXE004",
    "PIE790",
    "PIE808",
    "RET501",
    "SIM102",
    "SIM103",
    "SIM115",
    "SIM117",
    "SIM118",
    "SIM210",
    "SIM211",
    "I001",
    "N999",
    "W605",
    "D419",
    "PLC0206",
    "PLC0414",
    "PLR1704",
    "PLR1711",
    "PLW0127",
    "PLW1510",
    "UP004",
    "UP006",
    "UP007",
    "UP008",
    "UP022",
    "UP024",
    "UP026",
    "UP030",
    "UP031",
    "UP032",
    "UP034",
    "UP035",
    "UP037",
    "UP039",
    "UP045",
    "RUF010",
    "RUF012",
    "RUF013",
    "RUF059",
    "FURB136",
    "FURB192",
    "TRY002",
    "TRY004",
    "TRY201"
]
