target-version = "py310"

[lint]
ignore = [
    # flake8-bugbear
    "B",

    # flake8-comprehensions
    "C4",

    # flynt
    "FLY",

    # logging-format
    "G",

    # import conventions
    "ICN",

    # logging
    "LOG",

    # perflint
    "PERF",

    # flake8-pie
    "PIE",

    # flake8-return
    "RET",

    # Ruff-specific rules
    "RUF",

    # flake8-simplify
    "SIM",

    # pyupgrade
    "UP",
]
